# Documentation: https://github.com/yshui/picom/wiki
# Config created by Keyitdev https://www.github.com/keyitdev/dotfiles

fading = true;
fade-in-step = 0.015;
fade-out-step = 0.1;
fade-delta = 5;

backend = "glx";

corner-radius = 10; 

rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'Rofi'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

blur-method = "dual_kawase";
blur-strength = 4;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;

vsync = true;

detect-transient = true;

log-level = "debug";

opacity-rule = [
  "95:class_g = 'Org.gnome.Nautilus'",
  "90:class_g = 'kitty'",
  "80:class_g = 'Pcmanfm'",
  "90:class_g = 'vesktop'",
  "100:class_g = 'VirtualBoxVM'",
  "100:class_g = 'VirtualBox Machine'"
];

blur-background-exclude = [
  "class_g = 'VirtualBoxVM'",
  "class_g = 'VirtualBox Machine'",
  "class_g = 'Polybar'"
];

shadow-exclude = [
  "class_g = 'VirtualBoxVM'",
  "class_g = 'VirtualBox Machine'"
];

# animation settings

animations = true;

animation-for-open-window = "zoom";
animation-for-menu-window = "slide-down";
animation-for-transient-window = "slide-down";
animation-for-unmap-window = "slide-out";

animation-for-minimize = "squeeze";

animation-for-window-move = "wiggle";
animation-for-window-resize = "wiggle";
animation-for-window-menu = "wiggle";

animation-for-workspace-switch-in = "slide-up";
animation-for-workspace-switch-out= "slide-down";


animation-stiffness = 50;
animation-dampening = 4;
animation-window-mass = 0.2;
#animation-delta = 10;
animation-clamping = false;

animation-wiggle-influence = 35.0;

transition-length = 300;
transition-pow-x = 0.1;
transition-pow-y = 0.1;
transition-pow-w = 0.1
transition-pow-h = 0.1
size-transition = true;

use-damage = true;
