# Font
font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
font_size        12.0

# Cursor
cursor_shape     beam
cursor_blink     on

# Dracula Color Scheme
foreground       #F8F8F2
background       #282A36
selection_foreground #44475A
selection_background #F8F8F2
url_color        #8BE9FD

# Black
color0           #000000
color8           #6272A4

# Red
color1           #FF5555
color9           #FF6E6E

# Green
color2           #50FA7B
color10          #69FF94

# Yellow
color3           #F1FA8C
color11          #FFFFA5

# Blue
color4           #BD93F9
color12          #D6ACFF

# Magenta
color5           #FF79C6
color13          #FF92DF

# Cyan
color6           #8BE9FD
color14          #A4FFFF

# White
color7           #BFBFBF
color15          #FFFFFF

# Background opacity (slight transparency)
background_opacity  0.90

# Optional: remove window borders and tweak padding
hide_window_decorations no 
window_padding_width  8

# Optional: enable ligatures and better rendering
#
enable_ligatures     yes

# window size
remember_window_size no 
initial_window_height 30c 
initial_window_width 100c 

# position

placement_strategy center



confirm_os_window_close 0
